nelmio_api_doc:
    areas:
        default:
            path_patterns: [ ^/api/products, ^/api/users ]
    documentation:
        info:
            title: MileBo Api
            description: An api for all customer of MileBo service
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []